name: New release action
run-name: ${{ github.repository }} release ${{ github.ref_name }}

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  CreateEasyConfigForRelease:
    name: Create EasyConfig in take-it-easyconfig repo for new depad-utils release.
    runs-on: ubuntu-slim
    environment: releases
    steps:
      #  - name: Checkout
      #    uses: actions/checkout@v3
      #    with:
      #      persist-credentials: false
      #      fetch-depth: 0
      #  - name: Restore timestamps
      #    uses: chetan/git-restore-mtime-action@v1
      # - name: Get release details.
      #   id: get_release_details
      #   shell: bash
      #   run: |
      #         set -e
      #         set -u
      #         set -o pipefail
      #         printf 'GITHUB_SHA: %s\n' "${GITHUB_SHA}"
      #         printf 'GITHUB_REF: %s\n' "${GITHUB_REF}"
      #         year="$(date '+%y')"
      #         month="$(date '+%m')"
      # - name: Tarball url
      #   run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
      - name: Send pull-request
        run: |
              ORGANISATION='molgenis'
              REPOSITORY='take-it-easyconfigs'
              MODULE_NAME="${{ github.event.repository.name }}"
              MODULE_VERSION="${{ github.ref_name }}"
              BRANCH="${MODULE_NAME}/${MODULE_VERSION}"
              CHECKSUM="$(curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz" | shasum -a 256 | cut -d " " -f 1)"
              #
              # Clone the remote repository.
              #
              git clone \
                  --depth=1 \
                  --branch=main \
                  "https://github.com/${ORGANISATION}/${REPOSITORY}.git"
              cd "${REPOSITORY}"
              #
              # Configure committer identity.
              #
              #git config user.email "some-user@some-domain.com"
              git config user.name "github-new-release-action[bot]"
              #
              # Create a new feature branch for the changes.
              #
              git checkout -b "${BRANCH}"
              #
              # Create/update the EasyConfig.
              #
              cat << ENDOFEASYCONFIG > "${MODULE_NAME:0:1}/${MODULE_NAME}/${MODULE_NAME}-${MODULE_VERSION}.eb"
              name = '${MODULE_NAME}'
              version = '${MODULE_VERSION}'

              homepage = 'https://github.com/${ORGANISATION}/${MODULE_NAME}/'
              description = """Utilities for deploy admins to manage HPC environments."""

              toolchain = SYSTEM
              easyblock = 'CmdCp'

              source_urls = [('https://github.com/${ORGANISATION}/%s/archive/' % (name))]
              sources = [('%s.tar.gz' % (version))]
              checksums = ['${CHECKSUM}']

              local_executables = [
                  'GetPerlModuleDepTreeFromCPAN.pl',
                  'generateEasyConfig.R',
                  'hpc-environment-sync.bash',
                  'module-usage'
              ]

              files_to_copy = [
                  'README.md',
                  'LICENSE',
                  (['bin/*'], 'bin/')
              ]

              #
              # We don't really need a command to install depad-utils, 
              # but as we have to have one in order to recycle the CmdCp easyblock... just ls.
              #
              cmds_map = [('.*', "echo 'Skipping install command.'")]

              #
              # Make scripts executable.
              # (Mode may by masked by umask.)
              #
              postinstallcmds = [
                  'for executable in $(ls -1 "%(installdir)s/bin/"* 2> /dev/null | grep -v ".cfg"); do chmod 775 "${executable}"; done',
                  'chmod -R g+rwX,o+rX,o-w "%(installdir)s/"*'
              ]

              #
              # Sanity checking.
              #
              sanity_check_paths = {
                  'files': ['README.md'] + ['bin/%s' % x for x in local_executables],
                  'dirs': ['bin']
              }
              sanity_check_commands = [('hpc-environment-sync.bash', '-h')]

              moduleclass = 'tools'
              ENDOFEASYCONFIG
              #
              # Commit changes and push feature branch to origin.
              #
              git add "${MODULE_NAME:0:1}/${MODULE_NAME}/${MODULE_NAME}-${MODULE_VERSION}.eb"
              git commit -m "New/updated EasyConfig for ${MODULE_NAME}/${MODULE_VERSION}."
              git push origin "${BRANCH}"
              #
              # Authorize GitHub CLI and create PR.
              #
              gh auth login --with-token "${{ secrets.take_it_easyconfigs_pat }}"
              gh pr create \
                --body '' \
                --title "Auto PR: New/updated EasyConfig for ${MODULE_NAME}/${MODULE_VERSION}." \
                --head "${BRANCH}" \
                --base 'main'